# please note, do NOT split this section - it will break the application
# the security section MUST be defined in one place, and cannot be overwritten
security:
    firewalls:
        secured_area:
            pattern: .*
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   logout
                target: /%locale%
                invalidate_session: true
                success_handler: hanzo.logout_success_handler

        login_firewall:
            pattern:    login
            anonymous:  ~

    access_control:
        - { path: ^/.*/i18n/js, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/.*/payment/dibs/callback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/account/password-forgotten, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/.*/admin, roles: ROLE_EMPLOYEE }
        - { path: ^/fx, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_CONSULTANT, ROLE_EMPLOYEE] }

    providers:
        main:
            propel:
                class: Hanzo\Model\Customers
                property: email

    encoders:
        Hanzo\Model\Customers:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
