# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "squeeze64"
  config.vm.box_url = "http://www.emken.biz/vagrant-boxes/debsqueeze64.box"
  config.vm.network :hostonly, "192.168.200.200"
  config.vm.share_folder "www-hanzo", "/var/www/hanzo", "../../../", :nfs => true
  config.vm.provision :shell, :path => "skel-files/provisioning.sh", :args => "un"
end
